### PR TITLE
Add Debian Jessie compat for Artifactory PRO, support external pg db.

### PR DESCRIPTION
**Pull request by rasebo**
I moved things around, and added compatibility for Artifactory PRO on Debian Jessie, as well as the capability of using an external postgresql database. I also created empty task files for Debian HA and OSS that can be used in the future to expand functionality for this distro.

### CODE REVIEW

**Comment by rasebo** [comment]
... would be useful to test this on CentOS or RH. I haven't (sorry), and I am not sure I didn't break anything on it when moving around.

**Comment by rasebo** [comment]
Hmmmm, pull requests not welcome?

**Comment by bbaassssiiee** [comment]
I tried to test your branch with OSS Artifactory on Debian, but it is not being installed.

**defaults/main.yml:**
- update: postgres_jdbc_base now is "postgresql-9.4.1212.jre6"

**tasks/main.yml:**
please add the role-tag on each action so we can run the role by tag.

```
  tags:
    - artifactory
```

tasks/db/postgresql.yml: this is a bit fishy, but adding `become: yes` helped me
```
- name: 'create artifactory database user in postgres'
  become: yes
  become_user: postgres


- name: 'create artifactory database in postgres'
  become: yes
  become_user: postgres

- name: 'download jdbc connector for postgres'
  become: yes
```

tasks/dists/debian-xxxyml: please install openssl

**Comment by rasebo** [comment]
Ooops, sorry, I'll go ahead and fix it.

**Comment by bbaassssiiee** [comment]
Closed because inactive.

**Pull request closed without merging**
